# Changes here will be overwritten by Copier
_commit: 50e24e9
_src_path: https://github.com/Daemo00/Python-Package-Template-using-Copier
author_email: daemo00@gmail.com
author_full_name: Simone Rubino
cli: true
dependency: fastapi
optional_dependency: ''
package_name: TryHTMX
